site_name: Aioinject
site_description: Async-first python dependency injection library
repo_url: https://github.com/notypecheck/aioinject

strict: true

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
  not_found: warn

nav:
  - About: index.md
  - Usage Guide: usage-guide.md
  - Providers: providers.md
  - Extensions: extensions.md
  - Framework Integrations:
      - Aiogram: integrations/aiogram.md
      - Django: integrations/django.md
      - FastAPI: integrations/fastapi.md
      - Litestar: integrations/litestar.md
      - Strawberry GraphQL: integrations/strawberry-graphql.md
  - Internals:
      - Writing Custom Provider Extensions: internals/writing-custom-provider-extensions.md
      - Code Compilation: internals/code-compilation.md
  - Benchmarks: benchmarks.md


theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      toggle:
        icon: material/brightness-4

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      toggle:
        icon: material/brightness-7

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
